language: node_js
node_js: stable

branches:
  only:
  - hexo #or your source branch name
cache:
  directories:
  - node_modules #cache models to speed up the build

before_install:
- npm install -g hexo-cli

install:
- npm install

script:
- hexo generate

after_success: #remember to change name, email address, etc.
- git config --global user.name "yuening"
- git config --global user.email "n1085633848@outlook.com"
- sed -i'' - sed -i'' "s~git@github.com:yuening/yuening.github.io.git~https://${GH_TOKEN}@github.com/yuening/yuening.github.io.git~" _config.yml
- hexo d