language: node_js
node_js: 10.15.3

branches:
  only:
    - hexo

before_install:
- npm install -g hexo

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "yuening"
  - git config user.email "n1085633848@outlook.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master